name: upver

on:
  pull_request:
    branches:
      - master
    types: [closed]

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: check out dj7 repo
        uses: actions/checkout@v2
        with:
          path: main
      - name: check out upver repo
        uses: actions/checkout@v2
        with:
          repositoty: fuyutarow/UpVer
          path: upver
      - name: update version
        run: upver/musl/upver up -rz main/package.json
      - name: commit
        run: |
          cd main
          git commit -am "[GitHub Actions] Update version"
          git push
