# on:
#   push:
#     paths:
#       - "README.md"

on: [push]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Install dependencies
      run: npm install
    - name: Apply linter
      run: npm run lint --fix
    - name: Build the project
      run: npm run build
    - name: Deploy to firebase
      run: npx firebase deploy --token "${{ secrets.FIREBASE_TOKEN }}"
    # TODO: custom message
    # - name: Send a notification to discord
    #   uses: rtCamp/action-slack-notify@master
    #   env:
    #     SLACK_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
