name: Deploy to firebase

on:
  push:
    branches:
      - master
    paths:
      - "src/**"
      - "public/**"
      - "vue.config.js"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Install dependencies
      run: npm install
    - name: Apply linter
      run: npm run lint --fix
    - name: Build the project
      run: npm run build:prod
    - name: Deploy to firebase
      run: npx firebase deploy --token "${{ secrets.FIREBASE_TOKEN }}"
